### ISSUE TITLE
Add Licence

### ISSUE THREAD

**Issue by lduboeuf** [janbar/compass#1]
Hello,

Thanks for your app, i would love to publish it on Ubuntu Touch app store, but don't know which Licence you set.

**Comment by janbar** [comment]
Hi, the licence is GPL. I will update this repo to include missing license file.

**Comment by janbar** [comment]
LICENSE file has been added in the latest release 1.1.0

**Comment by lduboeuf** [comment]
Thank you. Your app is available in the open store :) https://open-store.io/app/compass.lduboeuf
